import * as authService from './js/services/auth-service.js';import * as chatService from './js/services/chat-service.js';import{listGameRooms,watchRoomPresence}from'./js/services/room-service.js?v=portal-rooms-1';
const $=s=>document.querySelector(s),modal=$('#loginModal'),messages=$('#messages'),stops=[];let user=null,profile=null,mode='signup',stopChat=null;const esc=v=>{const n=document.createElement('span');n.textContent=v??'';return n.innerHTML},initials=n=>(n||'나').trim().slice(0,1).toUpperCase();
function openLogin(){modal.hidden=false}function closeLogin(){modal.hidden=true}function status(t,ok=false){$('#authStatus').textContent=t;$('#authStatus').style.color=ok?'var(--mint)':''}function updateAuth(){const on=!!user;$('#loginOpen').hidden=on;$('#userMenu').hidden=!on;$('#chatLoginGate').hidden=on;$('#chatForm').hidden=!on;if(on){const n=profile?.nickname||user.user_metadata?.nickname||user.email?.split('@')[0]||'플레이어';$('#headerNickname').textContent=n;$('#headerAvatar').textContent=initials(n);$('#headerAvatar').className=`avatar ${profile?.avatar_color||authService.colorForUser(user.id)}`}}
async function applySession(s){user=s?.user||null;try{profile=user?await authService.getOrCreateProfile(user):null}catch{profile=null}updateAuth();renderMessages()}
async function loadRooms(){try{const rooms=await listGameRooms('roulette'),node=$('#rouletteRooms');node.innerHTML=rooms.map(r=>`<a class="room-entry" href="games/roulette/?room=${encodeURIComponent(r.roomId)}" data-room="${esc(r.roomId)}"><b>${esc(r.name)}</b><span><em data-count>0</em> / ${r.maxPlayers}</span><i>→</i></a>`).join('');rooms.forEach(r=>stops.push(watchRoomPresence({gameId:'roulette',roomId:r.roomId,onChange:({count})=>{const n=node.querySelector(`[data-room="${r.roomId}"] [data-count]`);if(n)n.textContent=count}})))}catch{$('#rouletteRooms').innerHTML='<span class="loading">방 목록을 불러오지 못했습니다.</span>'}}
function messageHTML(m){const mine=user?.id===m.user_id,c=['purple','mint','orange','blue'].includes(m.avatar_color)?m.avatar_color:'purple';return `<div class="message ${mine?'mine':''}" data-id="${m.id}"><span class="avatar ${c}">${esc(initials(m.nickname))}</span><div><p><b>${esc(m.nickname||'플레이어')}</b><time>${new Date(m.created_at).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</time>${mine?'<button class="message-delete">삭제</button>':''}</p><span>${esc(m.content)}</span></div></div>`}async function renderMessages(){try{const rows=await chatService.listMessages('lounge');messages.querySelectorAll('.message').forEach(n=>n.remove());rows.forEach(m=>messages.insertAdjacentHTML('beforeend',messageHTML(m)));messages.scrollTop=messages.scrollHeight}catch{}}function startChat(){stopChat?.();stopChat=chatService.subscribeToMessages('lounge',{onInsert:m=>{if(!messages.querySelector(`[data-id="${m.id}"]`))messages.insertAdjacentHTML('beforeend',messageHTML(m));messages.scrollTop=messages.scrollHeight},onDelete:m=>messages.querySelector(`[data-id="${m.id}"]`)?.remove()})}
$('#loginOpen').onclick=openLogin;$('#chatLoginGate').onclick=openLogin;$('#loginClose').onclick=closeLogin;modal.onclick=e=>{if(e.target===modal)closeLogin()};$('#communityOpen').onclick=()=>$('#community').classList.add('open');$('#chatClose').onclick=()=>$('#community').classList.remove('open');$('#userMenu').onclick=async()=>{if(confirm('로그아웃할까요?'))await authService.signOut()};$('#authMode').onclick=()=>{mode=mode==='signup'?'signin':'signup';const s=mode==='signup';$('#nicknameLabel').hidden=!s;$('#authNickname').required=s;$('#emailSubmit').textContent=s?'회원가입':'로그인';$('#authMode').innerHTML=s?'이미 계정이 있나요? <b>로그인</b>':'처음 오셨나요? <b>회원가입</b>';status('')};
$('#emailAuthForm').onsubmit=async e=>{e.preventDefault();status('처리 중…',true);try{const p={email:$('#authEmail').value.trim(),password:$('#authPassword').value,nickname:$('#authNickname').value.trim(),redirectTo:new URL('./',location.href).href},r=mode==='signup'?await authService.signUp(p):await authService.signIn(p);if(mode==='signup'&&!r.session){status('확인 메일을 보냈습니다.',true);return}closeLogin()}catch(x){status(x.message)}};$('#googleLogin').onclick=async()=>{try{await authService.signInWithProvider('google',new URL('./',location.href).href)}catch(x){status(x.message)}};$('#chatForm').onsubmit=async e=>{e.preventDefault();const i=$('#chatInput'),content=i.value.trim();if(!content||!user)return;await chatService.sendMessage({room:'lounge',userId:user.id,nickname:profile?.nickname||user.email?.split('@')[0]||'플레이어',avatarColor:profile?.avatar_color||authService.colorForUser(user.id),content});i.value=''};messages.onclick=async e=>{const b=e.target.closest('.message-delete');if(b)await chatService.deleteMessage(b.closest('.message').dataset.id,user.id)};
authService.onAuthChange(s=>applySession(s));await applySession(await authService.getSession());startChat();loadRooms();window.addEventListener('pagehide',()=>stops.splice(0).forEach(s=>s()));
