-- xfactoryx 초기 데이터 구조
-- Supabase Dashboard > SQL Editor에서 전체를 한 번 실행하세요.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null check (char_length(nickname) between 2 and 20),
  avatar_color text not null default 'purple',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room text not null default 'lounge' check (char_length(room) between 1 and 40),
  user_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null check (char_length(nickname) between 2 and 20),
  avatar_color text not null default 'purple',
  content text not null check (char_length(content) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists messages_room_created_at_idx
  on public.messages(room, created_at desc);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.messages from anon, authenticated;
grant select on table public.profiles to anon, authenticated;
grant insert, update on table public.profiles to authenticated;
grant select on table public.messages to anon, authenticated;
grant insert, delete on table public.messages to authenticated;
grant usage, select on sequence public.messages_id_seq to authenticated;

drop policy if exists "Public profiles are readable" on public.profiles;
create policy "Public profiles are readable"
  on public.profiles for select to anon, authenticated using (true);

drop policy if exists "Users create their own profile" on public.profiles;
create policy "Users create their own profile"
  on public.profiles for insert to authenticated
  with check ((select auth.uid()) = id);

drop policy if exists "Users update their own profile" on public.profiles;
create policy "Users update their own profile"
  on public.profiles for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "Messages are publicly readable" on public.messages;
create policy "Messages are publicly readable"
  on public.messages for select to anon, authenticated using (true);

drop policy if exists "Signed in users create their messages" on public.messages;
create policy "Signed in users create their messages"
  on public.messages for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users delete their own messages" on public.messages;
create policy "Users delete their own messages"
  on public.messages for delete to authenticated
  using ((select auth.uid()) = user_id);

do $$
begin
  alter publication supabase_realtime add table public.messages;
exception
  when duplicate_object then null;
end $$;
